version: "3.8"

services:
  # FastAPI Backend (Production)
  api:
    build: .
    ports:
      - "5000:8000"
    environment:
      - DATABASE_URL=sqlite:///./meeting_rooms.db
      - SECRET_KEY=your-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./meeting_rooms.db:/app/meeting_rooms.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development environment with hot reload
  api-dev:
    build: .
    ports:
      - "5001:8000"
    environment:
      - DATABASE_URL=sqlite:///./meeting_rooms.db
      - SECRET_KEY=dev-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    profiles:
      - dev

  # Test runner
  test:
    build: .
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=test-secret-key
      - TESTING=true
    volumes:
      - .:/app
    command: pytest tests/ -v
    profiles:
      - test
    depends_on: []
